### ISSUE TITLE
请问：仓库中有包括模态信息融合的模块吗？

### ISSUE THREAD

**Issue by JiayiFu** [Tencent/Lichee#3]
请问项目中有包括图片、文本、视频、音频等信息的modal fusion相关的模块吗？感谢。

**Comment by shawnx-w** [comment]
您好，感谢使用框架。
可以使用一下 examples/frame_title_fusion_embedding这个例子，将这个[data_tfrecord.zip](https://github.com/Tencent/Lichee/files/7410316/data_tfrecord.zip)里的两个文件放到对应的data文件夹下。这个数据量很小，只是用来保证框架测试通过。
具体的例子可以参考我们两个月前比赛(https://algo.browser.qq.com/) 中的赛道一，数据有60+G，其中涉及到视频标题，视频抽帧和音频转文本的多模态融合。

**Comment by JiayiFu** [comment]
收到，感谢您的回复，我找到对应的部分了，问题先关了。
